#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# MicroPython documentation build configuration file, created by
# sphinx-quickstart on Sun Sep 21 11:42:03 2014.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import sys
import os
import subprocess

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
sys.path.insert(0, os.path.abspath("."))

# =============================================================================
# Documentation versions and build date — bump these for each release.
# =============================================================================
import datetime as _dt

# OpenMV firmware version this documentation covers.
openmv_version = "5.0.0"

# MicroPython version that the firmware is built on top of.
# (Also used as the Sphinx ``version`` / ``release`` variables below.)
micropython_version = "1.28"

# Build date is computed automatically each time Sphinx runs. This English
# value is the default/fallback; setup() below replaces it per-build with a
# locale-formatted date (e.g. "17 يونيو 2026", "2026年6月17日") so the month
# name in the hero badge and footer is translated, not just the surrounding
# words.
_build_date_value = _dt.date.today()
build_date = _build_date_value.strftime("%d %b %Y")

# Values exposed to topindex.html and footer templates.
# Resolve this submodule's HEAD SHA at build time so "Edit this
# page" and the AI dropdown's raw-source link both pin to the exact
# commit that produced the page. The RST files physically live in
# openmv/micropython-doc — the parent openmv-doc repo only carries
# a submodule pointer, so GitHub blob URLs there 404. Falls back to
# "master" if `git` isn't available.
try:
    source_version = subprocess.check_output(
        ["git", "rev-parse", "HEAD"],
        cwd=os.path.dirname(os.path.abspath(__file__)),
        stderr=subprocess.DEVNULL,
    ).decode().strip()
except Exception:
    source_version = "master"

html_context = {
    "openmv_version": openmv_version,
    "micropython_version": micropython_version,
    "build_date": build_date,
    # "Edit this page" + AI raw-source links point at the submodule
    # repo where the RST source actually lives. The user-facing
    # navbar/footer GitHub icon is controlled separately by
    # html_theme_options["github_url"].
    "source_type": "github",
    "source_user": "openmv",
    "source_repo": "micropython-doc",
    "source_docs_path": "/docs/",
    "source_version": source_version,
}

# Site root — used by sphinx-llms-txt to emit absolute URLs in
# /llms.txt and by Shibuya's "Copy page" / "Open in ChatGPT" dropdown
# to fetch raw page source from /_sources/.
html_baseurl = "https://docs.openmv.io/"

# -- Landing page code examples (rendered via Pygments to match site code style) --
from pygments import highlight as _pygments_highlight
from pygments.lexers import PythonLexer as _PythonLexer
from pygments.formatters import HtmlFormatter as _HtmlFormatter

_landing_examples_src = {
    "yolo": '''
import csi
import time
import ml
from ml.postprocessing.ultralytics import YoloV8

csi0 = csi.CSI()
csi0.reset()
csi0.pixformat(csi.RGB565)
csi0.framesize(csi.VGA)
csi0.snapshot(time=2000)  # let AWB/AGC stabilize

# Built-in single-class person detector model.
model = ml.Model("/rom/yolov8n_192.tflite",
                 postprocess=YoloV8(threshold=0.4))
clock = time.clock()

while True:
    clock.tick()
    img = csi0.snapshot()
    # predict returns a list per class of ((x, y, w, h), score) tuples.
    for class_dets in model.predict([img]):
        for rect, score in class_dets:
            img.draw_rectangle(rect, color=(0, 255, 0))
    print(clock.fps(), "fps")
''',
    "apriltag": '''
import csi
import math
import time

csi0 = csi.CSI()
csi0.reset()
csi0.pixformat(csi.RGB565)
csi0.framesize(csi.QVGA)
csi0.snapshot(time=2000)  # let AWB/AGC stabilize
csi0.auto_gain(False)
csi0.auto_whitebal(False)

clock = time.clock()

while True:
    clock.tick()
    img = csi0.snapshot()
    for tag in img.find_apriltags():
        img.draw_detection(tag, color1=(255, 0, 0), color2=(0, 255, 0))
        deg = math.degrees(tag.rotation)
        print("ID %d  rotation %.1f deg" % (tag.id, deg))
    print(clock.fps(), "fps")
''',
    "blazeface": '''
import csi
import time
import ml
from ml.postprocessing.mediapipe import BlazeFace

csi0 = csi.CSI()
csi0.reset()
csi0.pixformat(csi.RGB565)
csi0.framesize(csi.VGA)
csi0.window((400, 400))  # square window for best results
csi0.snapshot(time=2000)  # let AWB/AGC stabilize

model = ml.Model("/rom/blazeface_front_128.tflite",
                 postprocess=BlazeFace(threshold=0.4))
clock = time.clock()

while True:
    clock.tick()
    img = csi0.snapshot()
    for rect, score, keypoints in model.predict([img]):
        img.draw_rectangle(rect, color=(0, 0, 255))
        ml.utils.draw_keypoints(img, keypoints, color=(255, 0, 0))
    print(clock.fps(), "fps")
''',
    "qrcode": '''
import csi
import time

csi0 = csi.CSI()
csi0.reset()
csi0.pixformat(csi.RGB565)
csi0.framesize(csi.QVGA)
csi0.snapshot(time=2000)  # let AWB/AGC stabilize
csi0.auto_gain(False)

clock = time.clock()

while True:
    clock.tick()
    img = csi0.snapshot()
    for code in img.find_qrcodes():
        img.draw_rectangle(code.rect, color=(255, 0, 0))
        print(code.payload)
    print(clock.fps(), "fps")
''',
    "color": '''
import csi
import time

csi0 = csi.CSI()
csi0.reset()
csi0.pixformat(csi.RGB565)
csi0.framesize(csi.QVGA)
csi0.snapshot(time=2000)  # let AWB/AGC stabilize
csi0.auto_gain(False)
csi0.auto_whitebal(False)

# LAB thresholds: (L_min, L_max, A_min, A_max, B_min, B_max)
thresholds = [
    (30, 100, 15, 127, 15, 127),   # red
    (30, 100, -64, -8, -32, 32),   # green
]

clock = time.clock()

while True:
    clock.tick()
    img = csi0.snapshot()
    for blob in img.find_blobs(thresholds, pixels_threshold=200):
        img.draw_rectangle(blob.rect, color=(255, 0, 0))
        img.draw_cross((blob.cx, blob.cy))
    print(clock.fps(), "fps")
''',
    "barcode": '''
import csi
import time

csi0 = csi.CSI()
csi0.reset()
csi0.pixformat(csi.GRAYSCALE)
csi0.framesize(csi.VGA)
csi0.window((640, 80))  # narrow strip for fast linear scanning
csi0.snapshot(time=2000)  # let AWB/AGC stabilize
csi0.auto_gain(False)
csi0.auto_whitebal(False)

clock = time.clock()

while True:
    clock.tick()
    img = csi0.snapshot()
    for code in img.find_barcodes():
        img.draw_rectangle(code.rect, color=(0, 255, 0))
        print(code.payload, "(quality %d)" % code.quality)
    print(clock.fps(), "fps")
''',
    "hand": '''
import csi
import time
import ml
from ml.postprocessing.mediapipe import HandLandmarks

csi0 = csi.CSI()
csi0.reset()
csi0.pixformat(csi.RGB565)
csi0.framesize(csi.VGA)
csi0.window((400, 400))  # square window for the model
csi0.snapshot(time=2000)  # let AWB/AGC stabilize

# Connections between the 21 keypoints — palm + 5 fingers.
hand_lines = ((0, 1), (1, 2), (2, 3), (3, 4), (0, 5), (5, 6),
              (6, 7), (7, 8), (5, 9), (9, 10), (10, 11), (11, 12),
              (9, 13), (13, 14), (14, 15), (15, 16), (13, 17), (17, 18),
              (18, 19), (19, 20), (0, 17))

model = ml.Model("/rom/hand_landmarks_full_224.tflite",
                 postprocess=HandLandmarks(threshold=0.4))
clock = time.clock()

while True:
    clock.tick()
    img = csi0.snapshot()
    # predict returns a list per hand: index 0 = left, index 1 = right.
    for detections in model.predict([img]):
        for rect, score, keypoints in detections:
            ml.utils.draw_skeleton(img, keypoints, hand_lines,
                                   kp_color=(255, 0, 0),
                                   line_color=(0, 255, 0))
    print(clock.fps(), "fps")
''',
}

def _render_landing_code(src):
    return _pygments_highlight(
        src.strip(), _PythonLexer(),
        _HtmlFormatter(nowrap=False, cssclass="highlight"),
    )

html_context["landing_examples"] = {
    k: _render_landing_code(v) for k, v in _landing_examples_src.items()
}

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.doctest",
    "sphinx.ext.intersphinx",
    "sphinx.ext.mathjax",
    "sphinx.ext.todo",
    "sphinx.ext.coverage",
    # Auto-generates /llms.txt + /llms-full.txt during the build so LLMs
    # can discover and ingest the docs without any per-page maintenance.
    "sphinx_llms_txt",
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ["templates"]

# The suffix of source filenames.
source_suffix = ".rst"

# The encoding of source files.
# source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = "index"

# General information about the project.
project = "OpenMV MicroPython"
copyright = "The OpenMV MicroPython Documentation is Copyright © 2014-2026 by OpenMV, Damien P. George, and others."

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# We don't follow "The short X.Y version" vs "The full version, including alpha/beta/rc tags"
# breakdown, so use the same version identifier for both to avoid confusion.
version = release = micropython_version

# The source language. Translations are built by overriding this on the
# command line, e.g. ``-D language=zh_CN``.
language = "en"

# -- Options for i18n output ----------------------------------------------
locale_dirs = ["locale"]
gettext_compact = False
# Also extract ".. raw:: html" blocks (the changelog/quickstart cards and the
# quickref/sensors/shields tables) and image ":alt:" text so they translate.
# Deliberately NOT "literal-block" -- code examples must stay untranslated.
gettext_additional_targets = ["raw", "image"]

# Shibuya's navbar "Translations" switcher and the <link rel="alternate"
# hreflang> tags read this list. Each entry is
#   (display name, URL pattern with %s for the page, hreflang).
# English is the source language at the site root; each translation is a
# separate per-language build deployed under its own subdirectory. To
# produce one:
#
#   pip install sphinx-intl
#   sphinx-build -b gettext . _build/gettext        # extract .pot
#   sphinx-intl update -p _build/gettext -l zh_CN -l zh_TW
#   # ...translate locale/<lang>/LC_MESSAGES/*.po...
#   sphinx-build -b html -D language=zh_CN . _build/html/zh_CN
#   sphinx-build -b html -D language=zh_TW . _build/html/zh_TW
#
# The zh_CN / zh_TW entries below go live once those builds are deployed.
# English first (default), then A–Z by English language name.
html_context["languages"] = [
    ("English",    "/%s.html",       "en"),
    ("العربية",    "/ar/%s.html",    "ar"),       # Arabic
    ("简体中文",    "/zh_CN/%s.html", "zh-Hans"),  # Chinese (Simplified)
    ("繁體中文",    "/zh_TW/%s.html", "zh-Hant"),  # Chinese (Traditional)
    ("Hrvatski",   "/hr/%s.html",    "hr"),       # Croatian
    ("Čeština",    "/cs/%s.html",    "cs"),       # Czech
    ("Nederlands", "/nl/%s.html",    "nl"),       # Dutch
    ("Suomi",      "/fi/%s.html",    "fi"),       # Finnish
    ("Français",   "/fr/%s.html",    "fr"),       # French
    ("Deutsch",    "/de/%s.html",    "de"),       # German
    ("עברית",      "/he/%s.html",    "he"),       # Hebrew
    ("Magyar",     "/hu/%s.html",    "hu"),       # Hungarian
    ("Italiano",   "/it/%s.html",    "it"),       # Italian
    ("日本語",      "/ja/%s.html",    "ja"),       # Japanese
    ("한국어",      "/ko/%s.html",    "ko"),       # Korean
    ("Polski",     "/pl/%s.html",    "pl"),       # Polish
    ("Português",  "/pt_BR/%s.html", "pt-BR"),    # Portuguese
    ("Română",     "/ro/%s.html",    "ro"),       # Romanian
    ("Русский",    "/ru/%s.html",    "ru"),       # Russian
    ("Español",    "/es/%s.html",    "es"),       # Spanish
    ("Svenska",    "/sv/%s.html",    "sv"),       # Swedish
    ("Türkçe",     "/tr/%s.html",    "tr"),       # Turkish
]

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
# today = ''
# Else, today_fmt is used as the format for a strftime call.
# today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = [
    "build",
    "tools",
    ".venv",
    "esp32",
    "esp8266",
    "pyboard",
    "wipy",
    "library/_thread.rst",
    "library/btree.rst",
    "library/weakref.rst",
    "library/omv.uftpd.rst",
    "library/omv.utelnet.rst",
    "library/omv.uping.rst",
    "library/omv.umalloc.rst",
    "library/omv.cpufreq.rst",
    "library/esp.rst",
    "library/espnow.rst",
    "library/esp32.rst",
    "library/wm8960.rst",
    "library/zephyr.rst",
    "library/zephyr.DiskAccess.rst",
    "library/zephyr.FlashArea.rst",
    "library/zephyr.zsensor.rst",
    "library/lcd160cr.rst",
    "library/machine.ADCBlock.rst",
    "library/machine.ADCWiPy.rst",
    "library/machine.DAC.rst",
    "library/machine.SD.rst",
    "library/machine.TimerWiPy.rst",
    "library/machine.USBDevice.rst",
    "library/network.CC3K.rst",
    "library/network.PPP.rst",
    "library/network.WIZNET5K.rst",
    "library/network.WLANWiPy.rst",
    "library/pyb.Accel.rst",
    "library/pyb.LCD.rst",
    "library/pyb.Switch.rst",
    "library/wipy.rst",
    "reference/pyboard.py.rst",
    "mimxrt/general.rst",
    "mimxrt/pinout.rst",
    "mimxrt/tutorial/intro.rst",
    "mimxrt/quickref.rst",
    "renesas-ra/general.rst",
    "renesas-ra/quickref.rst",
    "renesas-ra/tutorial/index.rst",
    "renesas-ra/tutorial/intro.rst",
    "renesas-ra/tutorial/program_in_flash.rst",
    "renesas-ra/tutorial/reset.rst",
    "renesas-ra/tutorial/troubleshooting.rst",
    "renesas-ra/tutorial/using_peripheral.rst",
    "rp2/general.rst",
    "rp2/quickref.rst",
    "rp2/tutorial/intro.rst",
    "rp2/tutorial/pio.rst",
    "rp2/tutorial/reset.rst",
    "samd/general.rst",
    "samd/quickref.rst",
    "samd/pinout.rst",
    "samd/tutorial/intro.rst",
    "unix/quickref.rst",
    "zephyr/general.rst",
    "zephyr/quickref.rst",
    "zephyr/tutorial/index.rst",
    "zephyr/tutorial/intro.rst",
    "zephyr/tutorial/pins.rst",
    "zephyr/tutorial/repl.rst",
    "zephyr/tutorial/storage.rst",
]

# The reST default role (used for this markup: `text`) to use for all
# documents.
default_role = "any"

# If true, '()' will be appended to :func: etc. cross-reference text.
# add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
# add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
# show_authors = False

# Note: Shibuya overrides the Pygments style via its own theme.conf
# (`github-light-default` / `github-dark-default`), so we don't set
# ``pygments_style`` here.

# A list of ignored prefixes for module index sorting.
# modindex_common_prefix = []

# If true, keep warnings as "system message" paragraphs in the built documents.
# keep_warnings = False

# Global include files. Sphinx docs suggest using rst_epilog in preference
# of rst_prolog, so we follow. Absolute paths below mean "from the base
# of the doctree".
rst_epilog = """
.. include:: /templates/replace.inc
"""

# -- Options for HTML output ----------------------------------------------

html_theme = "shibuya"

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
html_theme_options = {
    "light_logo": "_static/openmv-logo-light.png",
    "dark_logo": "_static/openmv-logo-dark.png",
    "accent_color": "blue",
    "color_mode": "auto",
    "github_url": "https://github.com/openmv/openmv",
    "discussion_url": "https://forums.openmv.io/",
    "twitter_url": "https://x.com/openmvcam",
    "youtube_url": "https://www.youtube.com/channel/UCk43Dxy_qcwwYyLsP6EWatQ",
    "linkedin_url": "https://www.linkedin.com/company/16193624/",
    "globaltoc_expand_depth": 1,
    "toctree_collapse": True,
    "show_ai_links": True,
    "open_in_chatgpt": True,
    "open_in_claude": True,
    "open_in_perplexity": True,
    "nav_links": [
        {"title": "Home", "url": "index"},
        {"title": "Tutorial", "url": "openmvcam/tutorial/index"},
        {"title": "Libraries", "url": "library/index"},
        {"title": "Boards", "url": "openmvcam/quickref"},
        {"title": "Shields", "url": "openmvcam/shields"},
        {"title": "Sensors", "url": "openmvcam/sensors"},
        {"title": "Language", "url": "reference/index"},
        {"title": "CPython", "url": "genrst/index"},
        {"title": "Internals", "url": "develop/index"},
        {"title": "Changelog", "url": "changelog/index"},
        {"title": "License", "url": "license"},
    ],
}

# Add any paths that contain custom themes here, relative to this directory.
# html_theme_path = ['.']

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
# html_title = None

# A shorter title for the navigation bar.  Default is the same as html_title.
# html_short_title = None

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
html_logo = "static/openmv-logo-dark.png"

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
html_favicon = "static/openmv.ico"

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["static"]

# Add a custom CSS file for HTML generation
html_css_files = [
    "custom.css",
]
# Client-side locale auto-selection: redirect first-time visitors to the
# build matching their browser language (English at root is the fallback),
# while honouring an explicit choice from the "Translations" switcher. Loaded
# in <head> so the swap happens before paint. See static/lang-redirect.js.
html_js_files = [
    "lang-redirect.js",
]
# Add any extra paths that contain custom files (such as robots.txt or
# .htaccess) here, relative to this directory. These files are copied
# directly to the root of the documentation.
# html_extra_path = []

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
html_last_updated_fmt = "%d %b %Y"

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
# html_use_smartypants = True

# Custom sidebar templates, maps document names to template names.
# html_sidebars = {}

# Additional templates that should be rendered to pages, maps page names to
# template names.
html_additional_pages = {"index": "topindex.html"}

# If false, no module index is generated.
# html_domain_indices = True

# If false, no index is generated.
# html_use_index = True

# If true, the index is split into individual pages for each letter.
# html_split_index = False

# If true, links to the reST sources are added to the pages.
# html_show_sourcelink = True

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
# html_show_sphinx = True

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
# html_show_copyright = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
# html_use_opensearch = ''

# This is the file name suffix for HTML files (e.g. ".xhtml").
# html_file_suffix = None

# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #'papersize': 'letterpaper',
    # The font size ('10pt', '11pt' or '12pt').
    #'pointsize': '10pt',
    # Additional stuff for the LaTeX preamble.
    #'preamble': '',
    # Include 3 levels of headers in PDF ToC
    "preamble": r"\setcounter{tocdepth}{2}",
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (
        master_doc,
        "OpenMV-MicroPython.tex",
        "OpenMV MicroPython Documentation",
        "OpenMV, Damien P. George, and others",
        "manual",
    ),
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
# latex_logo = None

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
# latex_use_parts = False

# If true, show page references after internal links.
# latex_show_pagerefs = False

# If true, show URL addresses after external links.
# latex_show_urls = False

# Documents to append as an appendix to all manuals.
# latex_appendices = []

# If false, no module index is generated.
# latex_domain_indices = True

# Enable better Unicode support so that `make latexpdf` doesn't fail
latex_engine = "xelatex"

# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (
        "index",
        "openmv-micropython",
        "OpenMV MicroPython Documentation",
        ["OpenMV, Damien P. George, and others"],
        1,
    ),
]

# If true, show URL addresses after external links.
# man_show_urls = False

# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        master_doc,
        "OpenMV-MicroPython",
        "OpenMV MicroPython Documentation",
        "OpenMV, Damien P. George, and others",
        "OpenMV-MicroPython",
        "OpenMV firmware documentation, built on MicroPython.",
        "Miscellaneous",
    ),
]

# Documents to append as an appendix to all manuals.
# texinfo_appendices = []

# If false, no module index is generated.
# texinfo_domain_indices = True

# How to display URL addresses: 'footnote', 'no', or 'inline'.
# texinfo_show_urls = 'footnote'

# If true, do not generate a @detailmenu in the "Top" node's menu.
# texinfo_no_detailmenu = False

# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {"python": ("https://docs.python.org/3", None)}


# =============================================================================
# Per-language build date
# =============================================================================
def setup(app):
    """Localize the build date for each language build.

    ``build_date`` in ``html_context`` is computed once at import time with an
    English month abbreviation. Each translation is a separate Sphinx run with
    ``-D language=<lang>``, so by the time a page is rendered we know the target
    language and can reformat the date with Babel — giving a natural localized
    date (month names, ordering, and digits) in the hero badge and footer
    instead of "17 Jun 2026" everywhere.
    """
    from babel.dates import format_date

    def localize_build_date(app, pagename, templatename, context, doctree):
        lang = (app.config.language or "en").replace("-", "_")
        try:
            context["build_date"] = format_date(
                _build_date_value, format="long", locale=lang
            )
        except Exception:
            pass  # unknown locale -> keep the English default already in context

    def localize_nav_links(app, pagename, templatename, context, doctree):
        # The navbar (Shibuya's ``theme_nav_links``) renders the configured
        # titles verbatim -- they are not gettext-wrapped, so they would stay
        # English in every translation. Run each title through the loaded
        # catalog here; titles that have a translation in sphinx.po (Tutorial,
        # Libraries, ...) get localized, proper nouns (OpenMV, CPython) pass
        # through unchanged because gettext returns the msgid when untranslated.
        nav = context.get("theme_nav_links")
        translator = getattr(app, "translator", None)
        if not nav or translator is None:
            return

        def tr(node):
            out = dict(node)
            if out.get("title"):
                out["title"] = translator.gettext(out["title"])
            if out.get("children"):
                out["children"] = [tr(c) for c in out["children"]]
            return out

        context["theme_nav_links"] = [tr(link) for link in nav]

    app.connect("html-page-context", localize_build_date)
    app.connect("html-page-context", localize_nav_links)
    return {"parallel_read_safe": True, "parallel_write_safe": True}
